### ISSUE TITLE
If there is anything I can help

### ISSUE THREAD

**Issue by Y-jiji** [elrnv/tensr#2]
This summer I decided to develop a general purpose sparse tensor computation toolkit in rust. 
Then I searched github for `sparse tensor lang:rust` to see if there is anyone doing something similar. 
It seems like this repo is the only entry popping up and it has been a while since you update anything in this project. 
I think sparse tensor computation can model a wide range of computational problems, and I don't want this project to abort. 
Let me know if I can help maintain this repository.

**Comment by elrnv** [comment]
Hi @Y-jiji, it is very exciting to see interest in supporting general purpose sparse tensors in Rust. I think this is absolutely an area that needs some love in Rust-land. Currently there is quite a bit of work dedicated to dense linear algebra (e.g. [ndaarray](https://docs.rs/ndarray/latest/ndarray/), [nalgebra](https://github.com/dimforge/nalgebra/tree/dev), [faer](https://github.com/sarah-ek/faer-rs)), but not much work on sparse linear algebra.
To the best of my knowledge, there are currently two main projects still active working on sparse matrices: [nalgebra-sparse](https://docs.rs/nalgebra-sparse/latest/nalgebra_sparse/) which lives [here](https://github.com/dimforge/nalgebra/tree/dev/nalgebra-sparse) and [sprs](https://github.com/sparsemat/sprs).

There is quite a lot you can do in sparse land, with `tensr`, I wanted to create lazily evaluated linear algebra system (like in the C++ [Eigen](https://eigen.tuxfamily.org/) library) that supported arbitrary sparse structures somewhat like in [taco](http://tensor-compiler.org/) but I think the goal was too ambitious and relied too heavily on the Rust trait system, making it very difficult to develop the library and keep it general. I think if you care about higher order tensors (or rather multidimensional arrays), and lazy evaluation then `tensr` can be a good reference point for what works well and what doesn't or even as a starting point. However, I think a better approach is to leverage procedural macros for generating optimized kernels (like in [taco](http://tensor-compiler.org/)) instead of relying on traits. I would be very happy to help out with another version of such a library, but sadly I don't have the bandwidth to continue with the development of `tensr`.

I believe [@Andlon](https://github.com/Andlon) has also experimented with a lazy linear algebra system, and maybe has some thoughts on this.

**Comment by Y-jiji** [comment]
I like your idea about laziness and making a kernel compiler in general. However, leveraging laziness in evaluation may not be a good idea. From my point of view, laziness is useful in that it taps into operator fusion at kernel compilation time. Anyway, I want to work from tensr as a starting point and thank you for sharing these helpful information about proceedings in this area.

**Comment by elrnv** [comment]
Sounds good! I'm happy to help, feel free to contact me by email if you want to discuss anything further.

> From my point of view, laziness is useful in that it taps into operator fusion at kernel compilation time

I am using "lazy evaluation" here in contrast to "eager evaluation" where the result of a single operation (e.g. matrix multiplication or addition) needs to be stored before being passed to the next operation, which is typically much more expensive for large systems. In contrast, in lazy evaluation you could do a single write for a more complex string of matrix operations. But, I 100% agree that by compiling kernels you have a lot more control (in my mind this is also lazy since evaluation is likewise delayed when compared to "eager evaluation").
